name = "NonLinearInterferometry"
uuid = "60b3c923-b586-4d94-8350-69d9cdb2a1e4"
authors = ["Ali <a_eghrari@yahoo.com> and contributors"]
version = "1.0.0-DEV"

[deps]

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"

[targets]
test = ["Test", "CSV", "Interpolations", "Downloads"]
